spring-cloud/spring-cloud-app-broker

.circleci/config.yml

Updating the caching strategy to consider the branch since we have a multigradle project.
`./gradlew dependencies` just displays root dependencies and since we have a multigradle project doesn't cache anything after running that command.
Updating comments by step name.

Updating CircleCI caching for multi-gradle projects

---

build.gradle
spring-cloud-app-broker-deployer-cloudfoundry/build.gradle
spring-cloud-app-broker-deployer/build.gradle

Adding artifactory gradle plugin.
Explicitly setting spring-boot-validator version instead of using the constrain until constrains allow publishing.
Deleting unnecessaries dependencyManagement import.
Upgrading gradle to 4.9.

Adding artifactory gradle plugin for SNAPSHOTS

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingApplication.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformationService.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformationServiceTest.java

Copy each BackingApplication before it enters the ParametersTransformer
chain, ensuring that transformations don't mutate the static
configuration of each app.
closes spring-cloud-incubator/spring-cloud-app-broker#88

Prevent transforms from accumulating across runs

---

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java
spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/UpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/UpdateServiceInstanceWorkflowTest.java

This is a really naive implementation of update. It's almost a straight
copy of the create workflow, so using it will cause app downtime. It's
not intended to be a final implementation, just something to fill the
gap until we can do this properly.

Implement service updates

---

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java
spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/DeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/UpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflowTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflowTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java

Allow implementing brokers to provide their own implementations of `CreateServiceInstanceWorkflow` , `DeleteServiceInstanceWorkflow`, and `UpdateServiceInstanceWorkflow` beans to perform operations in addition to app deployment. 
Fixes #81, #82, #89, #98

Multiple workflows

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java

Having `@Order` kind of implies sequential execution of update / create / delete flows. However with `flatMap` if lower order workflow completes first it will take precedence. `concatMap` will run the next flow only when the previous one is completed. 
Not sure if that should be a default behaviour. If we want some flexibility in here, we might need to provide some way to configure this behaviour.

Run service workflows sequentially

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingApplication.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/BackingApplicationTest.java

Closes https://github.com/spring-cloud-incubator/spring-cloud-app-broker/issues/107

Hide potentially sensitive logs output when serializing backing app

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingApplication.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/BackingApplicationTest.java

When BackingApplication is built from properties but not with the builder it might trigger NPE when logging.

Fix NPE when logging backing application

---

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceWithMultipleAppsAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceWithTargetAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java
spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java

Added TargetService to update flow
Added explicit assertion on backing app containin initial parameters afer an update
Updated AT to consider Updates with Target
Added ATs for multiple apps
Not failing when CF returns a DB error when creating a space
Not failing when space does not exist
Connected to #93

Fixing update flow with SpacePerServiceInstance

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java

to prevent logging of sensitive data by default.
Fixes #127

Use debug level logging for all logs that include request and response objects

---

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfiguration.java
spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/CredentialGenerator.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/SimpleCredentialGenerator.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/SpringSecurityBasicAuthCredentialProviderFactory.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/SpringSecurityOAuth2CredentialProviderFactory.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/credentials/SimpleCredentialGeneratorTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/credentials/SpringSecurityBasicAuthCredentialProviderFactoryTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/credentials/SpringSecurityOAuth2CredentialProviderFactoryTest.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/CredHubCredentialsGenerator.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java
spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/extensions/credentials/CredHubCredentialsGeneratorTest.java

- Add `CredHubCredentialsGenerator`
- Update `CredHubAutoconfiguration` to conditionally create beans
- Refactor the `CredentialGenerator` interface to be reactive
- Replace use of Pair in favor of Tuple2
Resolves #152

Add support to optionally generate secrets from CredHub

---

spring-cloud-app-broker-acceptance-tests/src/main/java/org/springframework/cloud/appbroker/acceptance/services/NoOpCreateServiceInstanceWorkflow.java
spring-cloud-app-broker-acceptance-tests/src/main/java/org/springframework/cloud/appbroker/acceptance/services/NoOpDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-acceptance-tests/src/main/java/org/springframework/cloud/appbroker/acceptance/services/NoOpUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceAppBindingWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceRouteBindingWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/DeleteServiceInstanceBindingWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/DeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/UpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflowTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java

Modify the `create()`, `update()`, and `delete()` methods on Workflow interfaces to: 
* Add a second `Response` parameter so these methods can act on the response provided by `buildResponse()` methods without having to keep track of state separately.
* Provide default implementations.

Improve Workflow method contract.

---

ci/scripts/manage-bosh-bbl-environment.sh
spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/CloudFoundryAppDeployerAutoConfiguration.java
spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java

This allows consuming libraries to provide beans of the same type without conflict

Use qualifiers when setting up cf deployer beans

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle
spring-cloud-app-broker-docs/build.gradle
spring-cloud-app-broker-docs/src/docs/asciidoc/index.adoc

`./gradlew docs` builds documentation in `spring-cloud-app-broker-docs/build/`.

Add dir and modify build task for reference docs

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingApplication.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/CredentialProviderSpec.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/ParametersTransformerSpec.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/ServicesSpec.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/TargetSpec.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/CreateInstanceWithServiceInstanceGuidSuffixTargetComponentTest.java

In order to avoid double mutation of the fields on BackingApplication the copy constructor was fixed to deep copy each collection instead of passing the references through
Added a second service instance creation to a component test
[Fixes #205]

Deep copying BackingApplication values

---

build.gradle
publish-maven.gradle
spring-cloud-app-broker-acceptance-tests/build.gradle
spring-cloud-app-broker-autoconfigure/build.gradle
spring-cloud-app-broker-core/build.gradle
spring-cloud-app-broker-deployer-cloudfoundry/build.gradle
spring-cloud-app-broker-deployer/build.gradle
spring-cloud-app-broker-docs/build.gradle
spring-cloud-app-broker-integration-tests/build.gradle
spring-cloud-app-broker-security-credhub/build.gradle
spring-cloud-starter-app-broker-cloudfoundry/build.gradle
spring-cloud-starter-app-broker/build.gradle

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://docs.oracle.com/javase/8/docs/api/ migrated to:  
https://docs.oracle.com/javase/8/docs/api/ ([https](https://docs.oracle.com/javase/8/docs/api/) result 200).
* http://docs.spring.io/spring/docs/ migrated to:  
https://docs.spring.io/spring/docs/ ([https](https://docs.spring.io/spring/docs/) result 200).
* http://www.apache.org/licenses/LICENSE-2.0 migrated to:  
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
* …

URL Cleanup

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DeployerClientTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/DeleteInstanceComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/DeleteInstanceWithServicesComponentTest.java

If backing apps or services are missing, then the error is logged and the
app name or service instance name is returned as if the service was deleted
as expected.
Resolves #208

Do not fail delete operation if backing apps or services are missing

---

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java
spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java

Making `ServiceInstanceStateRepository` and
`ServiceInstanceBindingStateRepository` both `@ConditionalOnMissingBean`
allows App Broker consumers to easily override the default in-memory
implementation with their own.

Make StateRepository beans conditional

---

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryOperationsUtils.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java

- `CloudFoundryOperationUtils` was accessing the default org
to get operations, which in some cases wasn't correct, e.g.
when getting a service instance not created in the default org.
To solve this problem, we're now exposing a new method `getOperationsForOrgAndSpace`,
which gets the operations in the organization and space specified.

Find organization to access service instance

---

spring-cloud-app-broker-acceptance-tests/README.adoc
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryClientConfiguration.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/uaa/UaaService.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/CreateInstanceWithSpacePerServiceInstanceTargetComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/CloudControllerStubFixture.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-feature-flag-roles.json

When using the space per service instance strategy, currently the OAuth
client requires `cloud_controller.admin` privileges to deploy apps and
services to a new space. This commit adds support for dynamically granting
the space developer role to a client which has the org manager role but not
admin privileges.
Resolves #203

Dynamically add space developer role for non-admin clients

---

spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc

Credential providers take a mapping, not a sequence of mappings.

Fix credential-provider examples

---

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/UpdateInstanceWithUpgradeComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/CloudControllerStubFixture.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-packages-READY.json

Before every update-service call would upgrade the backing application.
This changes will only create a new application package when the `upgrade` flag is provided as an `-c` parameter.

Adding support for service instance upgrade

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepository.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepository.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepositoryTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepositoryTest.java

Resolves #254
The added tests are flaky with the old implementation and may result in the following stacktrace during execution, which is the result of a concurrent modification of the non-threadsafe HashMap:
```
java.lang.AssertionError: expectation "expectNextCount(100000)" failed (expected: count = 100000; actual: counted = 516; signal: onError(java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')))
at reactor.test.ErrorFormatter.assertionError(ErrorFormatter.java:105)
at reactor.test.ErrorFormatter.failPrefix(ErrorFormatter.java:94)
at reactor.test.ErrorFormatter.fail(ErrorFormatter.java:64)
at …
```

Fix concurrency issue with InMemory state repositories

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingAppDeploymentService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingServicesProvisionService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/manager/BackingAppManagementService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/manager/ManagementClient.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingDeleteServiceInstanceBindingWorkflow.java

Before only error message was dispalyed in logs providing no information, like exception details or stacktrace. Now error message is logged together with exception, including stacktrace.

Make error reporting more verbose

---

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java

Having multiple domains is supported by CAPI and `domain` is just a configuration
shortcut. However for compatibility reasons existing `domain` property
can't be removed, instead new `domains` property is added. When both are
provided in the request or default properties, `domains` will take priority.

Add domains property

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java

After adding this change. A lot of our tests started becoming flaking in environments with low resources. Such as in some pipelines. If the tests get executed in parallel in a machine with less memory, some of the tests start to fail:
```
FAILED test: org.springframework.cloud.appbroker.service.WorkflowServiceInstanceBindingServiceTest > createServiceInstanceRouteBindingWithAsyncError()
FAILED test: org.springframework.cloud.appbroker.service.WorkflowServiceInstanceBindingServiceTest > deleteServiceInstanceBinding()
WorkflowServiceInstanceServiceTest. updateServiceInstance()
```
Because of that reason, we want to revert back until we can explain why is this failing. It could be just a matter of the way the code is tested and not the actual code.
This reverts commit …

Revert "Fix blocking calls to workflow layers"

---

build.gradle
spring-cloud-app-broker-autoconfigure/build.gradle
spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfiguration.java
spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfigurationTest.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/CredentialGenerator.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/WiremockServerFixture.java
spring-cloud-app-broker-security-credhub/build.gradle
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/extensions/credentials/CredHubCredentialsGenerator.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java
spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingDeleteServiceInstanceBindingWorkflow.java
spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/extensions/credentials/CredHubCredentialsGeneratorTest.java
spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflowTest.java
spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingDeleteServiceInstanceBindingWorkflowTest.java

- Replace the use of the imperative Spring CredHub APIs in favor of the
reactive alternatives.
- Build against the latest Spring CredHub snapshots
- Increase heap memory for component tests

Use Reactive Spring CredHub APIs

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/TargetSpec.java

This PR provides an implementation for TargetSpec equals() and hashCode() as provided by intellij java7 template.
This supports the #285 and the dynamic catalog, to be able to compare BrokeredService which invoke TargetSpec.equals
https://github.com/spring-cloud/spring-cloud-app-broker/blob/b0c71e52de361ef097c3a6e27e9d63b291a6ed4c/spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BrokeredService.java#L106

TargetSpec equals and hashcode

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflowTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/CreateInstanceWithOnlyABackingServiceComponentTest.java

As discussed in https://github.com/spring-cloud/spring-cloud-app-broker/issues/285, this PR provides the ability to exposed a brokered services which has backing services but not backing applications.

Support brokered service without backing application

---

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc

By default cf-java-client will set a default completion timeout of 5 Mins.
The api-polling-timeout property now enables a configureable value
applied in create/update/delete service instance CF API calls for
backing services.
See https://github.com/spring-cloud/spring-cloud-app-broker/issues/285 for more background on related use-case

Configurable API polling duration to support async backing services

---

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java
spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java

This PR enables application built ontop of SCAB to provide custom BrokeredServices bean.
This supports a use-case described in #285 , in particular a dynamically generated catalog, see more details into https://github.com/orange-cloudfoundry/osb-cmdb-spike#dynamic-catalog and https://github.com/orange-cloudfoundry/osb-cmdb-spike/pull/1

Support custom BrokeredServices to be injected by custom configuration

---

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceWithServiceInstanceGuidSuffixTargetAcceptanceTest.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/targets/ServiceInstanceGuidSuffix.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/targets/TargetServiceTest.java

Truncate app name if too long when using `ServiceInstanceGuidSuffix`

---

build.gradle

- Correct the javadoc exclusion path to the acceptance and integration tests
- Remove starters, docs and test jars from distribution zip
Resolves #269

Do not include tests in docs and distribution zips

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepository.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepository.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepositoryTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepositoryTest.java

To avoid blocking from time to time: #313 this commit replaces the Map implementation by a ConcurrentSkipListMap, it might not be the most efficient way to store this information, but, considering the order of magnitude we are dealing with and, the fact that the reading time is around logaritmic, should be good enough for this use case.
[Finishes #313]

Replacing InMemory Map data structure

---

CONTRIBUTING.adoc

Document use of intellij codestyle to format import as expected by gradle build
Relates to #346 although more changes might be required such as the followings which do not seem to be currently in sync with project code or PR reviews
> Make sure all new .java files to have a simple Javadoc class comment with at least an @author tag identifying you, and preferably at least a paragraph on what the class is for.

Document use of intellij codestyle to format import

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java

Unlike provisioning / deprovisioning, binding can be a fully synchronous
operation, i.e. it should fully complete within a request lifecycle.
There is no need to update service instance state or run create / delete
workflows in a parallel scheduler.
The existing flow should still be enabled for async binding.

Run sync binding / unbinding operations synchronously

---

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java

Currently App Broker allows users to specify mutually exclusive
manifest properties - specifically `routes` along with any combination
of the deprecated `host`, `hosts`, `domain` and `domains`. This change
makes `routes` take precedence if specified.

Routes property overrides conflicting app manifest properties

---

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/DeleteInstanceWithAppsAndServicesComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java

When a service instance is deleted, all configured backing services will
be deleted as well as all services bound to any backing applications
Resolve #344

Fix an issue where configured backing services are not being deleted

---

spring-cloud-app-broker-acceptance-tests/src/main/java/org/springframework/cloud/appbroker/acceptance/ManagementController.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/AppManagementRestageAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/AppManagementRestartAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/AppManagementStartAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/AppManagementStopAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CloudFoundryAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceWithServiceInstanceGuidSuffixTargetAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceWithServicesAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceWithSpacePerServiceInstanceTargetAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/UpdateInstanceWithNewServiceAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/UpdateInstanceWithServicesAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryClientConfiguration.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryService.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/UserCloudFoundryService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/manager/BackingAppManagementService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/manager/BackingAppManagementServiceWithServiceInstanceIdTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/CreateInstanceWithOAuth2CredentialsComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/DeleteInstanceComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/DeleteInstanceWithAppsAndServicesComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/DeleteInstanceWithServicesComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/UpdateInstanceWithNewServiceComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/UpdateInstanceWithServicesComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/UpdateInstanceWithServicesParametersComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/UpdateInstanceWithServicesRebindComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java

Calling /v2/service_instance/<id> requires the broker client to be
either space developer of a user's space or have `cloud_controller.admin`
authority. To remove this requirement, BackingAppManagementService was
updated to accept service and plan name as arguments, so now getting
these values is a responsibility of a caller. In case of update / delete
both values can be extracted from the request, for management operations
they now have to be provided.
Also, this commit introduces ATs refactoring to make sure App Broker can
work without `cc.admin` permissions and without being a org manager.
This is done by separating CloudFoundryService to User and Broker
implementations. UserCloudFoundryService can only create / update /
delete service instances in own space and org, which broker UAA …

Remove CAPI call to get service name and plan

---

build.gradle

A description must be provided in order to produce the correct metadata
that is required by maven central.

Add check to fail the build if a submodule is missing a description

---

ci/pipeline.yml
ci/pr-pipeline.yml
ci/tasks/acceptance-tests.yml

This can make use of the global Concourse registry mirror, which is
authenticated to avoid DockerHub rate limits.
#403

Replace docker-image resource with registry-image

---

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryClientConfiguration.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryService.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/uaa/UaaService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingAppDeploymentService.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java
spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DefaultBackingAppDeploymentServiceTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DeployerClientTest.java
spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/AppDeployer.java

The update service flow is now:
1. pre-update backing applications
2. update backing services
3. update backing applications
The Cloud Foundry implementation has a pre-update step which applies
backing application environment updates. This allows the following
backing services update step to read the updated app environment, which
is required for correct operation of some services where a rebind is
performed on update. The final update backing applications step performs
a rolling redeployment as before to ensure both environment changes and
any credential updates resulting from a rebind are propagated to the
backing apps.

Pre-update of backing applications

---

README.adoc
gradle.properties
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/WiremockComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-v3-app-STARTED.json

Updating compatibility matrix with SCOSB and OSBAPI versions
Updating default buildpack to empty String. Nulls are not allowed by operations and the only way to enable autodiscovery is by passing and empty list, passing an empty String will trigget that behaviour. Updating tests to document the default buildpack

Updating CFJC to 5.1

---

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CloudFoundryAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryClientConfiguration.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/uaa/UaaService.java

Previously we recreate client before each test. When multiple tests are running concurrently, if a token is issued for test A but the client was deleted during test B, then the token used for test A would be an 'invalid token' and fail the test. Another error scenario is when test A and test B both trigger client creation at the same time, one of them would error out due to `client already exists`. This fix should avoid most of the risk in terms of client creation

Only recreate client if the existing client has different authorities

---

gradle.properties
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-deployment-DEPLOYED.json

State field was deprecated in CAPI and starting from CFJC 5.3 marked as nullable, since it won't be sent by CAPI versions 3.91+.
App Broker should use status field instead.

Use status field to check deployment status instead of state

---

ci/pipeline.yml
ci/pr-pipeline.yml
ci/tasks/build-project.yml
ci/tasks/distribute.yml
ci/tasks/promote.yml
ci/tasks/stage.yml
ci/tasks/sync-to-maven-central.yml

the migration to runway is still a work in progress
this PR...
- removes some hard-coded URLs
- uses corporate-harbor instead of dockerhub
- fixes the release-ci-image build

ci updates

---

ci/images/release-ci-image/Dockerfile
ci/pipeline.yml
ci/scripts/acceptance-tests.sh
scripts/clean-env.sh

`runaway` quota should not be required because the default toolsmiths quota is already very generous:
```
➜  spring-cloud-app-broker git:(gareth/toolsmith-env-for-ats) ✗ cf quotas
Getting quotas as admin...
OK
name      total memory   instance memory   routes   service instances   paid plans   app instances   route ports
default   100G           unlimited         1000     unlimited           allowed      unlimited       100
```
I also removed the `credhub login` step because I noticed that the credhub cli is warning that it's not actually necessary given all the credentials have already been set as env vars.

Create test orgs and spaces before ATs run

---

README.adoc
gradle.properties
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/WiremockComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-v3-app-STARTED.json

Updating compatibility matrix with SCOSB and OSBAPI versions
Updating default buildpack to empty String. Nulls are not allowed by
operations and the only way to enable autodiscovery is by passing and
empty list, passing an empty String will trigger that behaviour.
Updating tests to document the default buildpack
(cherry-pick of dc6c0c8ffeaeed2528e26bbbe85fb1662115c73f)

Updating CFJC to 4.15.0.BUILD-SNAPSHOT

---

ci/pipeline.yml

* Trigger builds nightly to drive out failures
* Add an 'all' group to the pipeline view to provide an overview
#449

Nightly builds (1.2.x)

---

ci/pipeline.yml

* Trigger builds nightly to drive out failures
* Add an 'all' group to the pipeline view to provide an overview
#449

Nightly builds (1.1.x)

---

ci/pipeline.yml

* Trigger builds nightly to drive out failures
* Add an 'all' group to the pipeline view to provide an overview
#449

Nightly builds (1.3.x)

---

gradle.properties
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-docs/build.gradle
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/WiremockComponentTest.java
spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-v3-app-STARTED.json

I think we picked up some unintended commits in this branch since the
last 1.1.x release tag and accidentally moved to Spring Boot 2.3.
Rolling back to the latest available versions in the correct release
series:
* CF Java Client 4.16.0.RELEASE
* Open Service Broker 3.1.2.RELEASE
* Spring Boot 2.2.13.RELEASE

Fix dependencies for the 1.1.x branch

---

ci/images/app-broker-ci/Dockerfile

Removes need to wait for releasing or building custom images from source.
Same as for...
* 1.3.x https://github.com/spring-cloud/spring-cloud-app-broker/pull/460
* 1.2.x https://github.com/spring-cloud/spring-cloud-app-broker/commit/6f211839d6686e0682c98f1a7634d0aefce3ba60

Bump to concourse-release-scripts-0.3.4-SNAPSHOT for 1.1.x

---

ci/images/app-broker-ci/Dockerfile

Removes need to wait for releasing or building custom images from source.

Bump to concourse-release-scripts-0.3.4-SNAPSHOT for 1.3.x

---

ci/pipeline.yml

Initially I was going to reuse the username secret, but that is required later for the branch creation, so we need to have 2 secrets one with the name and the other with the token.
The password is a placeholder required.

Use GH Tokens for pipelines

---

ci/scripts/acceptance-tests.sh

By default, cf-deployment uses minimal vm type, scaling the main components up vertically
to use large instead.

Scaling  vm types 1.2.x

---

ci/scripts/acceptance-tests.sh

By default, cf-deployment uses minimal vm type, scaling the main components up vertically
to use large instead.

Scaling vm types

---

ci/scripts/acceptance-tests.sh

By default, cf-deployment uses minimal vm type, scaling the main components up vertically
to use large instead.

Scaling  vm types 1.1.x

---

build.gradle

In order to exclude reading the gradle logs

Update nohttp to ignore daemon logs

---

settings.gradle

As per https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023

Removing releases repository

---

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc

In order to enable multiple buildpacks to be added to the backing application manifest

Adding buildpacks to deployer properties

---

build.gradle

Ignore build output in the checkstyle nohttp check. This prevents build output from other parallel tasks from causing the check to fail.

Fix checkstyle nohttp race

---

ci/scripts/acceptance-tests.sh

Because it makes the output in the Concourse UI messy

Don't use rich Gradle output for ATs

---

build.gradle
settings.gradle
spring-cloud-app-broker-acceptance-tests/build.gradle
spring-cloud-app-broker-autoconfigure/build.gradle
spring-cloud-app-broker-core/build.gradle
spring-cloud-app-broker-deployer-cloudfoundry/build.gradle
spring-cloud-app-broker-deployer/build.gradle
spring-cloud-app-broker-docs/build.gradle
spring-cloud-app-broker-integration-tests/build.gradle
spring-cloud-app-broker-logging/build.gradle
spring-cloud-app-broker-security-credhub/build.gradle

* This allows removing springBootVersion so that the actual version can be set only once in the boot plugin in 'settings.gradle'. This requires adding the boot plugin to all modules, modules that do not use use 'apply false' to only add the plugin libraries to the build runtime.
* Updated use of Gradle `enforcePlatform` with `plaform`. Is there any dependency that is in risk if we allow some boot dependency to be overridden buy another?
This will fix the inconsistency of dependabot updates, because we are getting 2 PRs for each Boot bump, instead of one with the updated version in all places.

(1.4.x) Remove spring boot duplication in configuration

---

build.gradle
settings.gradle
spring-cloud-app-broker-acceptance-tests/build.gradle
spring-cloud-app-broker-autoconfigure/build.gradle
spring-cloud-app-broker-core/build.gradle
spring-cloud-app-broker-deployer-cloudfoundry/build.gradle
spring-cloud-app-broker-deployer/build.gradle
spring-cloud-app-broker-docs/build.gradle
spring-cloud-app-broker-integration-tests/build.gradle
spring-cloud-app-broker-logging/build.gradle
spring-cloud-app-broker-security-credhub/build.gradle

This allows removing `springBootVersion` so that the actual version can be set only once in the boot plugin in 'settings.gradle'. This requires adding the boot plugin to all modules, modules that do not use use 'apply false' to only add the plugin libraries to the build runtime.
This will fix the inconsistency of dependabot updates, because we are getting 2 PRs for each Boot bump, instead of one with the updated version in all places.

(1.6.x) Remove Spring Boot duplication in configuration

---

build.gradle
settings.gradle
spring-cloud-app-broker-acceptance-tests/build.gradle
spring-cloud-app-broker-autoconfigure/build.gradle
spring-cloud-app-broker-core/build.gradle
spring-cloud-app-broker-deployer-cloudfoundry/build.gradle
spring-cloud-app-broker-deployer/build.gradle
spring-cloud-app-broker-docs/build.gradle
spring-cloud-app-broker-integration-tests/build.gradle
spring-cloud-app-broker-logging/build.gradle
spring-cloud-app-broker-security-credhub/build.gradle

This allows removing 'springBootVersion' so that the actual version can be set only once in the boot plugin in 'settings.gradle'. This requires adding the boot plugin to all modules, modules that do not use use 'apply false' to only add the plugin libraries to the build runtime.
This will fix the inconsistency of dependabot updates, because we are getting 2 PRs for each Boot bump, instead of one with the updated version in all places.

 (1.5.x) Remove Spring Boot duplication in configuration

---

settings.gradle

Replaces https://github.com/spring-cloud/spring-cloud-app-broker/pull/801

(2.0.x) Bump Spring Boot to v3.0.8

---

build.gradle

Since we deleted the credhub-security module as part of https://github.com/spring-cloud/spring-cloud-app-broker/commit/135e3496d112aff71e06a0a6a46777bac3f7e7c7, we don't need this dependency in the buildscript anymore

2.0.x Removing CredHub dependency from buildscript

---

build.gradle

Since we deleted the credhub-security module as part of https://github.com/spring-cloud/spring-cloud-app-broker/commit/135e3496d112aff71e06a0a6a46777bac3f7e7c7, we don't need this dependency in the buildscript anymore

Removing CredHub dependency from buildscript

---

spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc

Adding stack as a suported property

Improving CF deployer documentation

---

.github/dependabot.yml

`dependency-name` was slightly wrong, due to Boot version being managed via the plugin, rather than a normal dependency.

Only allow patch bumps to Spring Boot

---

settings.gradle
spring-cloud-app-broker-docs/build.gradle

* All plugins (convert, pdf, etc) are released together and compatibility between versions is not guaranteed.
So, this PR uses 'resolutionStrategy' to assign the same version to all plugins ensuring they are all aligned
* Bump asciidoctor gradle plugins to 4.0.1

(2.0.x) Use Gradle resolutionStrategy to align asciidoctor plugin versions

---

settings.gradle
spring-cloud-app-broker-docs/build.gradle

* All plugins (convert, pdf, etc) are released together and compatibility between versions is not guaranteed.
So, this PR uses 'resolutionStrategy' to assign the same version to all plugins ensuring they are all aligned
* Bump asciidoctor gradle plugins to 4.0.1

(1.6.x) Use Gradle resolutionStrategy to align asciidoctor plugin versions

---

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceAcceptanceTest.java
spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/UpgradeInstanceAcceptanceTest.java
spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java
spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-v3-app-STARTED.json

Moving all references from cflinuxfs3 to cflinuxfs4.
Most of the cf deployments don't have any other stack aside from cflinuxfs4, moved the assertions to check on 4.

Removing stack assertion in ATs

---

settings.gradle
spring-cloud-app-broker-docs/build.gradle

* All plugins (convert, pdf, etc) are released together and compatibility between versions is not guaranteed.
So, this PR uses 'resolutionStrategy' to assign the same version to all plugins ensuring they are all aligned
* Bump asciidoctor gradle plugins to 4.0.1

(2.1.x) Use Gradle resolutionStrategy to align asciidoctor plugin versions

---

settings.gradle
spring-cloud-app-broker-docs/build.gradle

* All plugins (convert, pdf, etc) are released together and compatibility between versions is not guaranteed.
So, this PR uses 'resolutionStrategy' to assign the same version to all plugins ensuring they are all aligned
* Bump asciidoctor gradle plugins to 4.0.1

(2.2.x) Use Gradle resolutionStrategy to align asciidoctor plugin versions
