spring-cloud/spring-cloud-app-broker

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/AppBrokerTestProperties.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/BrokerProperties.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/BrokerPropertiesParameterResolver.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/DeleteInstanceAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java
Replacing test properties with `AppBrokerTestProperties` annotation.
=> Junit5 test properties

spring-cloud-app-broker-acceptance-tests/src/test/resources/logback.xml, spring-cloud-app-broker-autoconfigure/src/test/resources/logback.xml, spring-cloud-app-broker-core/src/test/resources/logback.xml, spring-cloud-app-broker-deployer-cloudfoundry/src/test/resources/logback.xml, spring-cloud-app-broker-deployer/src/test/resources/logback.xml, spring-cloud-app-broker-sample/src/test/resources/logback.xml
Boot 2 defaults to debug and logs out environment variables etc. Need a logback config to fix this
=> Ensure all tests are set to run at info level

README.adoc, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceWithParametersAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/CreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/DefaultParametersTransformer.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/ParametersTransformer.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/CreateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithCreationParametersComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithCustomCreationParametersComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/fixtures/OpenServiceBrokerApiFixture.java
=> Adding environment variable from create-service params

.gitignore, ci/README.md, ci/bbl-bosh-lite-environment/bbl-state/bbl-state.json.tmpl, ci/bbl-bosh-lite-environment/bbl-state/director-vars-store.yml.tmpl, ci/config.yml, ci/scripts/export-envvars-to-circle-ci.sh, ci/scripts/populate-secrets-from-environment.sh, ci/scripts/update-route53.sh, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java
repave bosh lite environment
update ci readme to include repave instructions
change `getServiceInstace()` so that no exception thrown if none found
=> Re-enable acceptance tests

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceWithParametersAcceptanceTest.java, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingApplication.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/ParametersTransformerSpec.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/AbstractExtensionFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/ConfigurationBeanUtils.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/ExtensionFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformationService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformerFactory.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactoryTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformationServiceTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithCreationParametersComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithCustomCreationParametersComponentTest.java
Finishes #91 
This should lay the groundwork for parameters transformers and other extension points to be configured with parameters to control their behavior.
=> Allow parameters transformers to accept configuration.

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceAppBindingWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceRouteBindingWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java
=> Add service instance binding workflows

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/DeleteServiceInstanceBindingWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java
=> Add service instance unbinding workflows

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepository.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/ServiceInstanceBindingStateRepository.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/event/InMemoryServiceInstanceBindingStateRepositoryTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java
=> Persist state for service binding and unbinding operations

build.gradle, spring-cloud-app-broker-acceptance-tests/build.gradle, spring-cloud-app-broker-sample/build.gradle
=> Remove appbroker from group id and exclude artifacts

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceWithServicesAndTargetAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceWithTargetAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceWithTargetAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingApplication.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BrokeredService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/targets/SpacePerServiceInstance.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/targets/Target.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/targets/TargetService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/targets/TargetServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/CreateServiceInstanceRequest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/DeleteServiceInstanceRequest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithServicesAndTargetComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithTargetComponentTest.java
Deploy all the backing apps of a given service to a single space
Deploying backing service instances to a space dedicated to the service instance
Connected to #133 
Finishes #94
=> Deploying backing service instances to a space

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/BackingApplicationsParametersTransformationService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/BackingServicesParametersTransformationService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParameterMappingParametersTransformerFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformationService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformer.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformerFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/PropertyMappingParametersTransformerFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/BackingApplicationsParametersTransformationServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/BackingServicesParametersTransformationServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactoryTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/ParameterMappingParametersTransformerFactoryTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/ParametersTransformationServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/PropertyMappingParametersTransformerFactoryTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/CreateServiceInstanceRequest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithCustomCreationParametersComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/CreateInstanceWithServicesParametersComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/fixtures/CloudControllerStubFixture.java, spring-cloud-app-broker-sample/src/test/resources/responses/cloudcontroller/get-info.json
Generalizing ParameterTransformers
Attempting to clean up before each test
Adding support for nested objects structure as parameters
Adding version to the mocked get-info response
Finishes #139
=> Adding parameter transformer to backing services

build.gradle, settings.gradle, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java, spring-cloud-app-broker-autoconfigure/build.gradle, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/main/resources/META-INF/spring.factories, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java, spring-cloud-app-broker-sample/src/main/resources/application-local.yml, spring-cloud-app-broker-sample/src/test/resources/application-appbroker-cf.yml, spring-cloud-app-broker-sample/src/test/resources/application.yml, spring-cloud-app-broker-security-credhub/build.gradle, spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java, spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflowTest.java
=> Store binding credentials in CredHub when available

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceWithServicesAcceptanceTest.java, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DeployerClientTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/DeleteServiceInstanceRequest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/UpdateServiceInstanceRequest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/UpdateServiceInstanceResponse.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/UpdateInstanceWithServicesComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/UpdateInstanceWithServicesParametersComponentTest.java, spring-cloud-app-broker-sample/src/test/java/org.springframework.cloud.appbroker/sample/fixtures/CloudControllerStubFixture.java
=>  Update backing service instances on update service.

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepository.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepository.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/ServiceInstanceState.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepositoryTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepositoryTest.java
=> Save last updated timestamp when persisting instance or binding states

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfigurationTest.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfigurationTest.java
=> Conditionally create the WorkflowServiceInstanceBindingService bean in auto-configuration.

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceAppBindingWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceRouteBindingWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/CreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/DeleteServiceInstanceBindingWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/DeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/UpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceServiceTest.java, spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java
=> Return Mono<Void> from Workflow API methods

build.gradle, spring-cloud-app-broker-acceptance-tests/build.gradle, spring-cloud-app-broker-core/build.gradle
Upgrading reactor and core
Pinning assertJ version
Finishes #160
=> Upgrading Spring Boot to 2.1.1

build.gradle, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryService.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
CFJC 3.14 allows for the remove of some custom polling on service updates.
=> Update CF Java Client and Spring CredHub dependencies.

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceWithServicesAcceptanceTest.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionServiceTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/UpdateServiceInstanceRequest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/CreateInstanceWithExistingServicesComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/CreateInstanceWithServicesAndTargetComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/CreateInstanceWithServicesParametersComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/DeleteInstanceWithServicesComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/UpdateInstanceWithServicesComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/UpdateInstanceWithServicesParametersComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/UpdateInstanceWithServicesRebindComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/CloudControllerStubFixture.java, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-service_binding.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-service_bindings.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/list-space-service_instances.json
=> Allow backing service instances to be unbound and rebound to backing apps on service instance update

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java
=> Ensure the exception message is logged in case of error.

ci/scripts/manage-bosh-bbl-environment.sh
This includes the ops file to enable Zero Down Time deploy
=> Add command for redeploying CF on bosh lite

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
Updating ATs to fail when invalid status
=> Fixing update when target specified

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfiguration.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfigurationTest.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/CreateBindingWithCredHubComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/DeleteBindingWithCredHubComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/WiremockComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/CredHubStubFixture.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/OpenServiceBrokerApiFixture.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/TestBindingCredentialsProviderFixture.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/WiremockServerFixture.java, spring-cloud-app-broker-integration-tests/src/test/resources/responses/credhub/get-data-find.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/credhub/post-permission.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/credhub/put-data-json.json, spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java, spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingDeleteServiceInstanceBindingWorkflow.java, spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingWorkflow.java, spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflowTest.java, spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingDeleteServiceInstanceBindingWorkflowTest.java
=> Set binding credential permissions in CredHub. Delete credentials on unbind.

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
=> Increasing default timeout

spring-cloud-app-broker-docs/src/docs/asciidoc/data-storage.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/example-service-broker.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/getting-started.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/index.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/introduction.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-bindings.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-broker-security.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
=> Begin reference

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingServiceTest.java
It is important to run user-provided and app-broker provided `buildResponse` methods sequentially according to `@Order` defined, similar to `create` methods. Certains flows (e.g. persisting credentials in CredHub) have to have previous flows (e.g. credentials generation) completed before run. Apart from minor refactoring to make flow testable (sadly through the package-private method) the only important change is switch from `flatMap` to `concatMap` when calling `buildResponse`.
=> Run buildResponse flows sequentially

spring-cloud-app-broker-docs/src/docs/asciidoc/advertising-services.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/data-storage.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/deployment-platforms.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/index.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-bindings.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-broker-security.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
=> First draft of reference documentation

spring-cloud-app-broker-docs/src/docs/asciidoc/deployment-platforms.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-bindings.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
From feedback on #200. Thanks @scottfrederick!
=> Updates to reference documentation

CODE_OF_CONDUCT.adoc, CONTRIBUTING.adoc, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/manager/BackingAppManagementServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
https://myfiles/app.jar ([https](https://myfiles/app.jar) result UnknownHostException).
https://myfiles/app1.jar ([https](https://myfiles/app1.jar) result UnknownHostException).
https://myfiles/app2.jar ([https](https://myfiles/app2.jar) result UnknownHostException).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended. …
=> URL Cleanup

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/DeploymentProperties.java
=> Add option to disable application start

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/UpdateInstanceAcceptanceTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java
- As the have to be whitelisted, for now we map only instances,
diskQuota and memory
=> Configure properties in backing app when updating instance

spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
Add information about create, update, and delete workflows with a caution
about certain update configurations causing downtime.
Resolves #231
=> Add docs for app deployment workflows

spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
target is an object, not an array
=> Fix target configuration example

build.gradle, gradle/wrapper/gradle-wrapper.properties
* Upgrading gradle to latest 4.13
=> Adding NoHttp check

spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/CreateInstanceWithOAuth2CredentialsAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org.springframework.cloud.appbroker.acceptance/fixtures/cf/CloudFoundryClientConfiguration.java
Including clients.write as an authority to the ATs client
=> Enabling OAuth2 Credentials AT

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactory.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactoryTest.java
=> Map Object value to JSON string in EnvironmentMappingParametersTransformer

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingService.java
=> Add missing "rebindOnUpdate" field to overridden default methods

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java
=> Invert workflow when deleting service instances

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingAppDeploymentService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingServicesProvisionService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingAppDeploymentService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingServicesProvisionService.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DefaultBackingAppDeploymentServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DefaultBackingServicesProvisionServiceTest.java
So developers can use custom implementation of deployers, in case if any customization of apps or services list is required.
=> Allow to override default service and app deployment services

build.gradle, spring-cloud-app-broker-core/build.gradle, spring-cloud-app-broker-deployer-cloudfoundry/build.gradle, spring-cloud-app-broker-integration-tests/build.gradle
Upgrading dependencies
Deleting bom overrides
Deleting spring platform references
Removing spring.io plugin 
Unpinning jetty version
=> Upgrading dependencies

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org.springframework.cloud.appbroker/integration/fixtures/CloudControllerStubFixture.java
=> Upgrades should not update environment

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java
=> Removing request from logging

spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java
This commit changes the default behaviour of `domains` property - instead of overriding `domain` it will merge values from both into a single list.
=> Allow to combine domains and domain properties

build.gradle, spring-cloud-app-broker-acceptance-tests/build.gradle, spring-cloud-app-broker-autoconfigure/build.gradle, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/CredHubAutoConfigurationTest.java, spring-cloud-app-broker-core/build.gradle, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/manager/BackingAppManagementServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/manager/ManagementClientTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppManagerTest.java, spring-cloud-app-broker-deployer/build.gradle, spring-cloud-app-broker-integration-tests/build.gradle, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/WiremockComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/WiremockServerFixture.java, spring-cloud-app-broker-security-credhub/build.gradle, spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflowTest.java
Upgrading mockito to match boots managed version
Removing JUnit vintage and duplicated dependencies
=> Bumping Spring Boot to 2.2.1.RELEASE

build.gradle, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerUpdateApplicationTest.java, spring-cloud-app-broker-integration-tests/build.gradle
- Upgrade to Spring Framework 5.2.2.RELEASE
- Upgrade to Reactor Dysprosium-SR2
- Upgrade to CF Java Client 4.2.0.RELEASE
=> Upgrade to Spring Boot 2.2.2.RELEASE

spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceBindingStateRepository.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/state/InMemoryServiceInstanceStateRepository.java, spring-cloud-app-broker-docs/build.gradle, spring-cloud-app-broker-docs/src/docs/asciidoc/index.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-bindings.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc, spring-cloud-app-broker-docs/src/test/java/com/example/appbroker/ExampleServiceInstanceBindingStateRepository.java, spring-cloud-app-broker-docs/src/test/java/com/example/appbroker/ExampleServiceInstanceStateRepository.java, spring-cloud-app-broker-docs/src/test/java/com/example/appbroker/ServiceInstance.java, spring-cloud-app-broker-docs/src/test/java/com/example/appbroker/ServiceInstanceBinding.java, spring-cloud-app-broker-docs/src/test/java/com/example/appbroker/ServiceInstanceBindingStateCrudRepository.java, spring-cloud-app-broker-docs/src/test/java/com/example/appbroker/ServiceInstanceStateCrudRepository.java
- Add example implementation in reference docs
- Include warning in javadoc and reference about using in mem implementation
in production
Resolves #257. Resolves #314
=> Document example implementation of ServiceInstanceStateRepository

spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java
=> Log warnings when auto-configuration enables an InMemory repository

spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/CreateInstanceWithCustomTargetComponentTest.java
=> Adding example on how to create a custom Target service

spring-cloud-app-broker-docs/build.gradle, spring-cloud-app-broker-docs/src/docs/asciidoc/deployment-platforms.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/getting-started.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/index.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/introduction.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-bindings.adoc, spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
Edited the docs for spelling, punctuation, usage, and code formatting.
Also updated the spring-doc-resources to the latest version
(from 0.2.0 to 0.2.1), to get a bug fix.
=> Editing pass and doc-resources upgrade

build.gradle, spring-cloud-app-broker-docs/build.gradle
Upgrade Asciidoctor to the latest version (3.1.0), to reduce technical debt.
=> Upgrade Asciidoctor

spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingDeleteServiceInstanceBindingWorkflow.java
=> Fix binding credentials permission deletion failure - AT free version

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingAppDeploymentService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingServicesProvisionService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/parameters/EnvironmentMappingParametersTransformerFactory.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/support/KebabCasePropertyBeanIntrospector.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/manager/BackingAppManagementService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/manager/ManagementClient.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceBindingService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/WorkflowServiceInstanceService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentCreateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppManager.java
- Only log potentially sensitive information in debug mode
- Apply consistent style
=> Improve logging

build.gradle
cfJavaClientVersion = "4.7.0.RELEASE"
junitPlatformLauncherVersion = "1.6.2"
checkstyleVersion = "8.33"
pmdVersion = "6.24.0"
=> Dependency version bumps

ci/pipeline.yml, ci/scripts/stage.sh
To prevent clashes with our Github branch protection rules
closes #388
=> Perform staging version bumps in a branch

build.gradle, ci/images/release-ci-image/Dockerfile, gradle.properties, scripts/set-pipelines.sh
* https://spring.io/blog/2020/04/30/updates-to-spring-versions
* Bump to SCOSB 3.2.0-RC1
closes #385
=> Switch to new Spring version scheme

scripts/clean-env.sh
Merging this to clean the PR environment and so we can continue to iterate on the script.
=> Add rough script for cleaning test environments

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/UpdateInstanceWithNewServiceAndTargetAcceptanceTest.java, spring-cloud-app-broker-autoconfigure/src/main/java/org/springframework/cloud/appbroker/autoconfigure/AppBrokerAutoConfiguration.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingSpaceManagementService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DefaultBackingSpaceManagementService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/DeployerClient.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/manager/BackingAppManagementService.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflow.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DefaultBackingSpaceManagementServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/deployer/DeployerClientTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/manager/BackingAppManagementServiceTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflowTest.java, spring-cloud-app-broker-core/src/test/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentUpdateServiceInstanceWorkflowTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerDeleteSpaceTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/AppDeployer.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/DeleteBackingSpaceRequest.java, spring-cloud-app-broker-deployer/src/main/java/org/springframework/cloud/appbroker/deployer/DeleteBackingSpaceResponse.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/CreateInstanceWithCustomTargetComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/CreateInstanceWithSpacePerServiceInstanceTargetComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/UpdateInstanceWithNewServiceAndTargetComponentTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/WiremockStubFixture.java, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/list-shared-domains.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/list-spaces.json
Also temporarily disable delete space on deleteServiceInstance.
=> Set target on bound services so deleteServiceInstance can target the right space

spring-cloud-app-broker-docs/src/docs/asciidoc/service-instances.adoc
=> docs: mention the use-spring-application-json property

gradle.properties
=> Bump to CF Java Client v5.6.0.RELEASE

gradle.properties
=> Bump to CF Java Client 4.16.0.RELEASE

ci/pipeline.yml
* Use GH tokens to push changes to repo
* Update artifact signature configuration
=> Update release pipeline to use GH token (1.1.x)

ci/pipeline.yml
* Use GH tokens to push changes to repo
* Update artifact signature configuration
=> Update release pipeline to use GH token (v1.2.x)

.github/dependabot.yml, build.gradle, gradle.properties, settings.gradle, spring-cloud-app-broker-acceptance-tests/build.gradle, spring-cloud-app-broker-docs/build.gradle, spring-cloud-app-broker-integration-tests/build.gradle
* dependabot.yml
* Move dependency version properties to build.gradle since dependabot
can't update other files
#436
=> Ensure Dependabot is working

.github/dependabot.yml, .github/workflows/build.yml, README.adoc, build.gradle, ci/config-concourse.yml, ci/pipeline.yml, ci/pr-pipeline.yml, ci/scripts/acceptance-tests.sh, ci/scripts/build-project.sh, ci/tasks/acceptance-tests.yml, ci/tasks/build-project.yml, ci/tasks/promote.yml, ci/tasks/stage.yml, ci/tasks/sync-to-maven-central.yml, gradle.properties, gradle/wrapper/gradle-wrapper.properties, scripts/set-pipelines.sh, spring-cloud-app-broker-acceptance-tests/build.gradle, spring-cloud-app-broker-integration-tests/build.gradle
=> Upgrading dependencies for 1.4

.github/dependabot.yml
Ignoring boot and open service broker latest versions in older branches
=> Removing 1.1 from dependabot

ci/scripts/build-project.sh, ci/tasks/build-project.yml
To re-enable snapshot publishing
=> Reverting distribution repository

.github/dependabot.yml
Updating milestone for 1.5
Using different name for spring boot
=> Fixing dependabot

ci/pipeline.yml, ci/tasks/acceptance-tests.yml, ci/tasks/build-project.yml, ci/tasks/promote.yml, ci/tasks/stage.yml, ci/tasks/sync-to-maven-central.yml, scripts/set-pipelines.sh
We do differentiate from the image tag used in CI and the branch we want to be targeting.
=> Splitting image tag from branch

ci/pr-pipeline.yml
It worked well on main pipeline, so applying to PR.
=> Splitting branch from ci image in PR pipeline

ci/pipeline.yml, ci/pr-pipeline.yml, ci/tasks/acceptance-tests.yml, ci/tasks/build-project.yml, ci/tasks/promote.yml, ci/tasks/stage.yml, ci/tasks/sync-to-maven-central.yml, scripts/set-pipelines.sh
Adding the split now so we can just bump a number in the future
=> Future proofing main with the tag split

ci/pipeline.yml
=> Adding missing tag

build.gradle
=> Upgrading scosb to 3.5.0

RELEASING.adoc
And to add how to recover from some common problems
=> Updating release docs to include extra checks

spring-cloud-app-broker-acceptance-tests/build.gradle, spring-cloud-app-broker-autoconfigure/build.gradle, spring-cloud-app-broker-core/build.gradle, spring-cloud-app-broker-deployer-cloudfoundry/build.gradle, spring-cloud-app-broker-deployer/build.gradle, spring-cloud-app-broker-docs/build.gradle, spring-cloud-app-broker-integration-tests/build.gradle, spring-cloud-app-broker-logging/build.gradle, spring-cloud-app-broker-security-credhub/build.gradle
Allowing consumer projects to apply their own version management
=> Remove enforcedPlatform dependency management

.editorconfig, ci/images/app-broker-ci/Dockerfile, ci/pipeline.yml, ci/pr-manager-pipeline.yml, ci/pr-pipeline.yml, ci/tasks/list-prs.yml, scripts/set-pipelines.sh
Use instanced pipelines for supported branches and PRs.
=> Instanced pipelines

.github/dependabot.yml, README.adoc
Updating readme with latest versions
=> Updating dependabot to reflect latest milestones

spring-cloud-app-broker-docs/build.gradle
to define the look and feel of the HTML output.
Part of Spring's continuing doc modernization effort.
=> Use spring-boot-backends

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceWithServicesSpacePerServiceInstanceTargetAcceptanceTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java
=> Fixing space parallelization

spring-cloud-app-broker-security-credhub/src/main/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflow.java, spring-cloud-app-broker-security-credhub/src/test/java/org/springframework/cloud/appbroker/workflow/binding/CredHubPersistingCreateServiceInstanceAppBindingWorkflowTest.java
`BindingStatus` enum has been removed.
=> Update to account for latest SCOSB changes

.github/dependabot.yml
Addressing [Issue#783](https://github.com/spring-cloud/spring-cloud-app-broker/issues/783)
=> (main) Add target branch to dependabot PR title

spring-cloud-app-broker-docs/build.gradle
#802
Replaces https://github.com/spring-cloud/spring-cloud-app-broker/pull/803
=> (1.6.x) Fix documentation build

spring-cloud-app-broker-docs/build.gradle
#802 
Replaces https://github.com/spring-cloud/spring-cloud-app-broker/pull/804
=> (1.5.x) Fix documentation build

spring-cloud-app-broker-docs/build.gradle
https://github.com/spring-cloud/spring-cloud-app-broker/issues/802
Repeat https://github.com/spring-cloud/spring-cloud-app-broker/pull/805 from repo branch
=> (1.4.x) Fix documentation build

.sdkmanrc, spring-cloud-app-broker-logging/build.gradle, spring-cloud-app-broker-security-credhub/build.gradle
CI pipelines have been failing for some time as seen from https://github.com/spring-cloud/spring-cloud-app-broker/pull/795
The errors pre-date the changes in Spring Boot configuration but CI data is already lost.
=> (1.6.x) Fix pipeline failures

settings.gradle
Manually since dependabot issue https://github.com/spring-cloud/spring-cloud-app-broker/issues/821
=> (2.0.x) Bump spring boot to v3.0.9

spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CloudFoundryAcceptanceTest.java, spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceAcceptanceTest.java, spring-cloud-app-broker-autoconfigure/src/test/java/org/springframework/cloud/appbroker/autoconfigure/CloudFoundryAppDeployerAutoConfigurationTest.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-app-broker-deployer-cloudfoundry/src/main/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryDeploymentProperties.java, spring-cloud-app-broker-deployer-cloudfoundry/src/test/java/org/springframework/cloud/appbroker/deployer/cloudfoundry/CloudFoundryAppDeployerTest.java, spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/fixtures/CloudControllerStubFixture.java, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-build-STAGED.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/get-stack.json, spring-cloud-app-broker-integration-tests/src/test/resources/responses/cloudcontroller/list-stacks.json
=> Adding stack support

ci/pipeline.yml
Adds Artifactory properties required for documentation publishing
=> Enable documentation publishing

ci/images/app-broker-ci/Dockerfile, ci/pipeline.yml, ci/scripts/promote.sh, ci/scripts/sync-to-maven-central.sh, ci/tasks/promote.yml, ci/tasks/sync-to-maven-central.yml
The jar file is no longer publicly available.
=> Switch to concourse-release-scripts image

ci/scripts/acceptance-tests.sh
* Sometimes cf login fails - this WIP will perform a retry
* But sometimes login succeeds and then a later command fails. We might need to extract the retry into a function and use it on every cf command?
=> Retry CF API login

build.gradle
Reverts spring-cloud/spring-cloud-app-broker#977
=> Revert "(2.1.x): Bump cfJavaClientVersion from 5.10.0.RELEASE to 5.12.0.RELEASE"
